name: Rust (vanessa-rs)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: docker
    image: ubuntu:latest

    steps:
    - uses: https://code.forgejo.org/actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
  format:
    runs-on: docker
    image: ubuntu:latest
    
    steps:
    - uses: https://code.forgejo.org/actions/checkout@v4
    - name: Formatting check
      run: rustfmt --edition 2021 --check -v src/*
